// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.20.1
// source: interaction/v1/interaction.proto

// 1. 定义 Protobuf 包名

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_interaction_v1_interaction_proto protoreflect.FileDescriptor

const file_interaction_v1_interaction_proto_rawDesc = "" +
	"\n" +
	" interaction/v1/interaction.proto\x12\x12api.interaction.v1B(Z&kratos-community/api/interaction/v1;v1b\x06proto3"

var file_interaction_v1_interaction_proto_goTypes = []any{}
var file_interaction_v1_interaction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_interaction_v1_interaction_proto_init() }
func file_interaction_v1_interaction_proto_init() {
	if File_interaction_v1_interaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_interaction_v1_interaction_proto_rawDesc), len(file_interaction_v1_interaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_interaction_v1_interaction_proto_goTypes,
		DependencyIndexes: file_interaction_v1_interaction_proto_depIdxs,
	}.Build()
	File_interaction_v1_interaction_proto = out.File
	file_interaction_v1_interaction_proto_goTypes = nil
	file_interaction_v1_interaction_proto_depIdxs = nil
}
