// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v3.20.1
// source: gateway/v1/gateway.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	v11 "kratos-community/api/content/v1"
	v1 "kratos-community/api/user/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationGatewayCreateArticle = "/api.gateway.v1.Gateway/CreateArticle"
const OperationGatewayDeleteArticle = "/api.gateway.v1.Gateway/DeleteArticle"
const OperationGatewayGetArticle = "/api.gateway.v1.Gateway/GetArticle"
const OperationGatewayLogin = "/api.gateway.v1.Gateway/Login"
const OperationGatewayRegisterUser = "/api.gateway.v1.Gateway/RegisterUser"
const OperationGatewayUpdateArticle = "/api.gateway.v1.Gateway/UpdateArticle"

type GatewayHTTPServer interface {
	// CreateArticle 转发到 Content 服务的 CreateArticle 接口
	CreateArticle(context.Context, *v11.CreateArticleRequest) (*v11.CreateArticleReply, error)
	// DeleteArticle 转发到 Content 服务的 DeleteArticle 接口
	DeleteArticle(context.Context, *v11.DeleteArticleRequest) (*v11.DeleteArticlReply, error)
	// GetArticle 转发到 Content 服务的 CreateArticle 接口
	GetArticle(context.Context, *v11.GetArticleRequest) (*v11.GetArticleReply, error)
	// Login 转发到 User 服务的 Login 接口
	Login(context.Context, *v1.LoginRequest) (*v1.LoginReply, error)
	// RegisterUser 转发到 User 服务的 Register 接口
	RegisterUser(context.Context, *v1.RegisterUserRequest) (*v1.RegisterUserReply, error)
	// UpdateArticle 转发到 Content 服务的 UpdateArticle 接口
	UpdateArticle(context.Context, *v11.UpdateArticleRequest) (*v11.UpdateArticleReply, error)
}

func RegisterGatewayHTTPServer(s *http.Server, srv GatewayHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/auth/login", _Gateway_Login1_HTTP_Handler(srv))
	r.POST("/v1/auth/register", _Gateway_RegisterUser1_HTTP_Handler(srv))
	r.POST("/v1/articles", _Gateway_CreateArticle1_HTTP_Handler(srv))
	r.GET("v1/articles/{id}", _Gateway_GetArticle1_HTTP_Handler(srv))
	r.PUT("v1/articles/{id}", _Gateway_UpdateArticle1_HTTP_Handler(srv))
	r.DELETE("v1/articles/{id}", _Gateway_DeleteArticle1_HTTP_Handler(srv))
}

func _Gateway_Login1_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.LoginRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayLogin)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Login(ctx, req.(*v1.LoginRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.LoginReply)
		return ctx.Result(200, reply)
	}
}

func _Gateway_RegisterUser1_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v1.RegisterUserRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayRegisterUser)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RegisterUser(ctx, req.(*v1.RegisterUserRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.RegisterUserReply)
		return ctx.Result(200, reply)
	}
}

func _Gateway_CreateArticle1_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v11.CreateArticleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayCreateArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateArticle(ctx, req.(*v11.CreateArticleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v11.CreateArticleReply)
		return ctx.Result(200, reply)
	}
}

func _Gateway_GetArticle1_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v11.GetArticleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayGetArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetArticle(ctx, req.(*v11.GetArticleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v11.GetArticleReply)
		return ctx.Result(200, reply)
	}
}

func _Gateway_UpdateArticle1_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v11.UpdateArticleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayUpdateArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateArticle(ctx, req.(*v11.UpdateArticleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v11.UpdateArticleReply)
		return ctx.Result(200, reply)
	}
}

func _Gateway_DeleteArticle1_HTTP_Handler(srv GatewayHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in v11.DeleteArticleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationGatewayDeleteArticle)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteArticle(ctx, req.(*v11.DeleteArticleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v11.DeleteArticlReply)
		return ctx.Result(200, reply)
	}
}

type GatewayHTTPClient interface {
	CreateArticle(ctx context.Context, req *v11.CreateArticleRequest, opts ...http.CallOption) (rsp *v11.CreateArticleReply, err error)
	DeleteArticle(ctx context.Context, req *v11.DeleteArticleRequest, opts ...http.CallOption) (rsp *v11.DeleteArticlReply, err error)
	GetArticle(ctx context.Context, req *v11.GetArticleRequest, opts ...http.CallOption) (rsp *v11.GetArticleReply, err error)
	Login(ctx context.Context, req *v1.LoginRequest, opts ...http.CallOption) (rsp *v1.LoginReply, err error)
	RegisterUser(ctx context.Context, req *v1.RegisterUserRequest, opts ...http.CallOption) (rsp *v1.RegisterUserReply, err error)
	UpdateArticle(ctx context.Context, req *v11.UpdateArticleRequest, opts ...http.CallOption) (rsp *v11.UpdateArticleReply, err error)
}

type GatewayHTTPClientImpl struct {
	cc *http.Client
}

func NewGatewayHTTPClient(client *http.Client) GatewayHTTPClient {
	return &GatewayHTTPClientImpl{client}
}

func (c *GatewayHTTPClientImpl) CreateArticle(ctx context.Context, in *v11.CreateArticleRequest, opts ...http.CallOption) (*v11.CreateArticleReply, error) {
	var out v11.CreateArticleReply
	pattern := "/v1/articles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGatewayCreateArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) DeleteArticle(ctx context.Context, in *v11.DeleteArticleRequest, opts ...http.CallOption) (*v11.DeleteArticlReply, error) {
	var out v11.DeleteArticlReply
	pattern := "v1/articles/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGatewayDeleteArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) GetArticle(ctx context.Context, in *v11.GetArticleRequest, opts ...http.CallOption) (*v11.GetArticleReply, error) {
	var out v11.GetArticleReply
	pattern := "v1/articles/{id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationGatewayGetArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) Login(ctx context.Context, in *v1.LoginRequest, opts ...http.CallOption) (*v1.LoginReply, error) {
	var out v1.LoginReply
	pattern := "/v1/auth/login"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGatewayLogin))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) RegisterUser(ctx context.Context, in *v1.RegisterUserRequest, opts ...http.CallOption) (*v1.RegisterUserReply, error) {
	var out v1.RegisterUserReply
	pattern := "/v1/auth/register"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGatewayRegisterUser))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *GatewayHTTPClientImpl) UpdateArticle(ctx context.Context, in *v11.UpdateArticleRequest, opts ...http.CallOption) (*v11.UpdateArticleReply, error) {
	var out v11.UpdateArticleReply
	pattern := "v1/articles/{id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationGatewayUpdateArticle))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
