// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v3.20.1
// source: gateway/v1/gateway.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v11 "kratos-community/api/content/v1"
	v1 "kratos-community/api/user/v1"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x18gateway/v1/gateway.proto\x12\x0eapi.gateway.v1\x1a\x12user/v1/user.proto\x1a\x18content/v1/content.proto\x1a\x1cgoogle/api/annotations.proto2\x9d\x05\n" +
	"\aGateway\x12V\n" +
	"\x05Login\x12\x19.api.user.v1.LoginRequest\x1a\x17.api.user.v1.LoginReply\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12n\n" +
	"\fRegisterUser\x12 .api.user.v1.RegisterUserRequest\x1a\x1e.api.user.v1.RegisterUserReply\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/auth/register\x12r\n" +
	"\rCreateArticle\x12$.api.content.v1.CreateArticleRequest\x1a\".api.content.v1.CreateArticleReply\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/v1/articles\x12j\n" +
	"\n" +
	"GetArticle\x12!.api.content.v1.GetArticleRequest\x1a\x1f.api.content.v1.GetArticleReply\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10v1/articles/{id}\x12v\n" +
	"\rUpdateArticle\x12$.api.content.v1.UpdateArticleRequest\x1a\".api.content.v1.UpdateArticleReply\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10v1/articles/{id}\x12r\n" +
	"\rDeleteArticle\x12$.api.content.v1.DeleteArticleRequest\x1a!.api.content.v1.DeleteArticlReply\"\x18\x82\xd3\xe4\x93\x02\x12*\x10v1/articles/{id}B$Z\"kratos-community/api/gateway/v1;v1b\x06proto3"

var file_gateway_v1_gateway_proto_goTypes = []any{
	(*v1.LoginRequest)(nil),          // 0: api.user.v1.LoginRequest
	(*v1.RegisterUserRequest)(nil),   // 1: api.user.v1.RegisterUserRequest
	(*v11.CreateArticleRequest)(nil), // 2: api.content.v1.CreateArticleRequest
	(*v11.GetArticleRequest)(nil),    // 3: api.content.v1.GetArticleRequest
	(*v11.UpdateArticleRequest)(nil), // 4: api.content.v1.UpdateArticleRequest
	(*v11.DeleteArticleRequest)(nil), // 5: api.content.v1.DeleteArticleRequest
	(*v1.LoginReply)(nil),            // 6: api.user.v1.LoginReply
	(*v1.RegisterUserReply)(nil),     // 7: api.user.v1.RegisterUserReply
	(*v11.CreateArticleReply)(nil),   // 8: api.content.v1.CreateArticleReply
	(*v11.GetArticleReply)(nil),      // 9: api.content.v1.GetArticleReply
	(*v11.UpdateArticleReply)(nil),   // 10: api.content.v1.UpdateArticleReply
	(*v11.DeleteArticlReply)(nil),    // 11: api.content.v1.DeleteArticlReply
}
var file_gateway_v1_gateway_proto_depIdxs = []int32{
	0,  // 0: api.gateway.v1.Gateway.Login:input_type -> api.user.v1.LoginRequest
	1,  // 1: api.gateway.v1.Gateway.RegisterUser:input_type -> api.user.v1.RegisterUserRequest
	2,  // 2: api.gateway.v1.Gateway.CreateArticle:input_type -> api.content.v1.CreateArticleRequest
	3,  // 3: api.gateway.v1.Gateway.GetArticle:input_type -> api.content.v1.GetArticleRequest
	4,  // 4: api.gateway.v1.Gateway.UpdateArticle:input_type -> api.content.v1.UpdateArticleRequest
	5,  // 5: api.gateway.v1.Gateway.DeleteArticle:input_type -> api.content.v1.DeleteArticleRequest
	6,  // 6: api.gateway.v1.Gateway.Login:output_type -> api.user.v1.LoginReply
	7,  // 7: api.gateway.v1.Gateway.RegisterUser:output_type -> api.user.v1.RegisterUserReply
	8,  // 8: api.gateway.v1.Gateway.CreateArticle:output_type -> api.content.v1.CreateArticleReply
	9,  // 9: api.gateway.v1.Gateway.GetArticle:output_type -> api.content.v1.GetArticleReply
	10, // 10: api.gateway.v1.Gateway.UpdateArticle:output_type -> api.content.v1.UpdateArticleReply
	11, // 11: api.gateway.v1.Gateway.DeleteArticle:output_type -> api.content.v1.DeleteArticlReply
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_v1_gateway_proto_init() }
func file_gateway_v1_gateway_proto_init() {
	if File_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_v1_gateway_proto_depIdxs,
	}.Build()
	File_gateway_v1_gateway_proto = out.File
	file_gateway_v1_gateway_proto_goTypes = nil
	file_gateway_v1_gateway_proto_depIdxs = nil
}
