// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratos-community/internal/conf"
	"kratos-community/internal/registry"
	"kratos-community/internal/relation/biz"
	"kratos-community/internal/relation/client"
	"kratos-community/internal/relation/data"
	"kratos-community/internal/relation/service"
	"kratos-community/internal/server"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, confRegistry *conf.Registry, logger log.Logger) (*kratos.App, func(), error) {
	grpcServer := server.NewGRPCServer(confServer, auth, logger)
	httpServer := server.NewHTTPServer(confServer, auth, logger)
	db, err := data.NewDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	redisClient, err := data.NewRedisClient(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(db, redisClient, logger)
	if err != nil {
		return nil, nil, err
	}
	relationRepo := data.NewRelationRepo(dataData, logger)
	discovery := registry.NewDiscovery(confRegistry)
	userClient, err := client.NewUserServiceClient(discovery)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	relationUsecase := biz.NewRelationUsecase(relationRepo, logger, auth, userClient)
	relationService := service.NewRelationService(relationUsecase)
	registrar := registry.NewRegistry(confRegistry)
	app := newApp(logger, grpcServer, httpServer, relationService, registrar)
	return app, func() {
		cleanup()
	}, nil
}
